services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:4000
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/parisos
      - SECRET_TOKEN_KEY=superUltraMegaSecretKey123
      - USE_OLLAMA=true
      - OLLAMA_API_URL=http://host.docker.internal:11434/api/chat
      - OLLAMA_MODEL=mistral 
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    command: sh -c "npm install && npm run dev"

  mongodb:
    image: mongo:6.0
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=parisos

volumes:
  mongodb_data:
